#!/usr/bin/env bash
# install nginx web server and create a html page
sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
