#!/usr/bin/env bash
# This script configures the nginx server to have a custom 404 page
# containing some string

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
sudo service nginx restart
