#!/usr/bin/env bash
# setup NGINX, redirects and 404

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
cm="rewrite ^/redirect_me https://https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;"
sudo sed -i "66i $cm" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
err="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "44i $err" /etc/nginx/sites-available/default
sudo service nginx start
