#!/usr/bin/env bash
# installs and configures a new Ubuntu machine nginx

sudo apt update
sudo apt install haproxy -y
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 160554-web-01 52.86.31.49:80 check
        server 160554-web-02 3.89.155.193:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start

