#!/usr/bin/env bash
# installs and configures a new Ubuntu machine nginx
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
apt-get update
sudo apt-get install haproxy=2.6.\*
echo "frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 160554-web-01 52.86.31.49:80 check
        server 160554-web-02 3.89.155.193:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
