#!/usr/bin/env bash
# FizzBuzz

i=1
while [ $i -le 100 ]; do
if (( i%5 == 0 )); then
echo "FizzBuzz"
elif (( i%5 == 0 )); then
echo "Buzz"
elif (( i%3 == 0 )); then
echo "Fizz"
else
echo "$i"
fi
i=$((i+1))
done
