#!/usr/bin/env bash

chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sed -i -e 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i -e 's/#user www-data;/user nginx;/g' -e 's/80/8080/g' /etc/nginx/nginx.conf /etc/nginx/sites-available/default
pkill -1 apache2
sudo -u nginx service nginx restart

